---
- block:

    - name: configure WSO2 EI executable files
      template:
        src: "{{ item }}.j2"
        dest: "{{ wso2ei_install_appdir_fullpath }}/{{ item }}"
        mode: 0754
      with_items: "{{ wso2ei_executable_files }}"
      when: wso2ei_enable_custom_configuration

    - name: configure WSO2 EI configuration validation files
      template:
        src: "{{ item }}.j2"
        dest: "{{ wso2ei_install_appdir_fullpath }}/{{ item }}"
      with_items: "{{ wso2ei_config_validation_files }}"
      when: wso2ei_enable_custom_configuration

    - name: configure WSO2 EI Carbon
      template:
        src: "{{ item }}.j2"
        dest: "{{ wso2ei_install_appdir_fullpath }}/{{ item }}"
      with_items: "{{ wso2ei_carbon_configuration_files }}"
      when: wso2ei_enable_custom_configuration

    - name: configure WSO2 EI Tomcat Catalina-Server
      template:
        src: "{{ item }}.j2"
        dest: "{{ wso2ei_install_appdir_fullpath }}/{{ item }}"
      with_items: "{{ wso2ei_tomcat_catalina_configuration_files }}"
      when: wso2ei_enable_custom_configuration

    - name: configure WSO2 EI Java Permission
      template:
        src: "{{ item }}.j2"
        dest: "{{ wso2ei_install_appdir_fullpath }}/{{ item }}"
      with_items: "{{ wso2ei_java_permission_configuration_files }}"
      when: wso2ei_enable_custom_configuration

    - name: configure WSO2 EI Master Datasources
      template:
        src: "{{ item }}.j2"
        dest: "{{ wso2ei_install_appdir_fullpath }}/{{ item }}"
      with_items: "{{ wso2ei_master_datasource_configuration_files }}"
      when: wso2ei_enable_custom_configuration

    - name: configure WSO2 EI User Management
      template:
        src: "{{ item }}.j2"
        dest: "{{ wso2ei_install_appdir_fullpath }}/{{ item }}"
      with_items: "{{ wso2ei_user_management_configuration_files }}"
      when: wso2ei_enable_custom_configuration

    - name: configure WSO2 EI Axis2
      template:
        src: "{{ item }}.j2"
        dest: "{{ wso2ei_install_appdir_fullpath }}/{{ item }}"
      with_items: "{{ wso2ei_axis2_configuration_files }}"
      when: wso2ei_enable_custom_configuration
  become: yes
  become_user: wso2